spring :
  profiles:
    active: dev
---
server:
  port: 8205
spring:
  profiles: dev
  application:
    name: config-client-dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8206
spring:
  profiles: test
  application:
    name: config-client-test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka




